<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <WarnOn>3390</WarnOn>
    <TargetFramework>net10.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <RepositoryUrl>https://github.com/leonitousconforti/flip7</RepositoryUrl>
    <FsDocsLicenseLink>https://github.com/leonitousconforti/flip7/blob/main/License.md</FsDocsLicenseLink>
    <FsDocsReleaseNotesLink>https://github.com/leonitousconforti/flip7/blob/main/RELEASE_NOTES.md</FsDocsReleaseNotesLink>
    <PackageProjectUrl>https://leonitousconforti.github.io/flip7</PackageProjectUrl>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="flip7.test" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="ScoreBuckets.fs" />
    <Compile Include="Card.fs" />
    <Compile Include="Hand.fs" />
    <Compile Include="Deck.fs" />
    <Compile Include="Strategy.fs" />
    <Compile Include="Simulate.fs" />
  </ItemGroup>

</Project>
